# Pipeline Configuration

# Storage configuration
storage:
    buckets:
        landing_zone: 'landing-zone'
        formatted_zone: 'formatted-zone'
        trusted_zone: 'trusted-zone'
        exploitation_zone: 'exploitation-zone'

    prefixes:
        temporal_landing: 'temporal_landing'
        persistent_landing_images: 'persistent_landing/images'
        persistent_landing_documents: 'persistent_landing/documents'
        formatted_images: 'images'
        formatted_documents: 'documents'
        trusted_images: 'images'
        trusted_documents: 'documents'
        trusted_reports: 'reports'

# Pipeline behavior
pipeline:
    dry_run: false
    overwrite: true
    batch_size: 256
    timeout: 60

# Monitoring
monitoring:
    enabled: true
    log_level: 'INFO'

# Hugging Face configuration
huggingface:
    skip_files: ['.gitattributes', '.gitignore', '.gitkeep']
    file_extensions:
        image: ['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'tiff']
        document: ['json', 'jsonl', 'ndjson']

# Image processing
image_processing:
    target_size: [512, 512]
    target_mode: 'RGB'
    target_format: 'JPEG'
    target_quality: 90

    quality_thresholds:
        min_width: 128
        min_height: 128
        min_aspect_ratio: 0.5
        max_aspect_ratio: 3.0
        blur_varlap_min: 50.0

    deduplication:
        enabled: true

# Document processing
document_processing:
    skip_fields: ['url', 'partition']
    always_tag: true

    nutrition:
        totals_key_candidates: ['nutrition_per100g', 'nutrition_totals']
        per_ingredient_key_candidates: ['nutrition_per_ingredient']
        numeric_fields: ['fat', 'salt', 'saturates', 'sugars']
        drop_totals_if_per_ingredient_present: true

    text_cleaning:
        language: 'english'
        remove_punctuation: true
        remove_stopwords: true

# ChromaDB configuration for documents
chromadb_documents:
    collection_name: 'exploitation_documents'
    embedding_model: 'Qwen/Qwen3-Embedding-0.6B'
    metadata: {}
    persist_dir: 'app/zones/exploitation_zone/chroma_documents'

# ChromaDB configuration for images
chromadb_images:
    collection_name: 'exploitation_images'
    embedding_model: 'OpenCLIP'
    metadata: {}
    persist_dir: 'app/zones/exploitation_zone/chroma_images'

chromadb_multimodal:
    collection_name: 'exploitation_multimodal'
    embedding_model: 'OpenCLIP'
    metadata: {}
    persist_dir: 'app/zones/exploitation_zone/chroma_multimodal'

# Multimodal tasks configuration
multimodal_tasks:
    text_chroma_persist_dir: 'app/zones/exploitation_zone/chroma_documents'
    image_chroma_persist_dir: 'app/zones/exploitation_zone/chroma_images'
    text_collection_name: 'exploitation_documents'
    image_collection_name: 'exploitation_images'
    text_embedding_model: 'Qwen/Qwen3-Embedding-0.6B'
    image_embedding_model: 'ViT-B-32'
    image_pretrained: 'laion2b_s34b_b79k'
    default_k: 5
    max_retrieved_images: 3
    ollama_host: 'http://localhost:11434'
    ollama_model: 'llava:7b'

# File paths configuration
file_paths:
    image_index: 'app/zones/landing_zone/image_index.json'
    recipes_index: 'app/zones/landing_zone/recipes_index.json'
    recipe_ids_with_images: 'app/zones/trusted_zone/recipe_ids_with_images.json'

# Transfer configuration for S3/MinIO
transfer:
    multipart_threshold: 8388608 # 8MB
    multipart_chunksize: 8388608 # 8MB
    max_concurrency: 4
    use_threads: true

# Testing limits (can be overridden)
testing:
    max_recipes: 1000
    max_processed: 50
